version: 3

includes:
  shared:
    taskfile: hack/common/Taskfile_cli.yaml
    flatten: true
    vars:
      CODE_DIRS: '{{.ROOT_DIR}}/cmd/... {{.ROOT_DIR}}/pkg/...'
      NAME: 'kw_kind'
      REPO_NAME: 'https://github.com/Diaphteiros/kw_kind'
      GENERATE_DOCS_INDEX: "true"
